repos:
-   repo: local
    hooks:

    -   id: format-check
        name: Format code check
        entry: docker compose exec -T app make format-check
        language: system
        always_run: true
        pass_filenames: false

    -   id: lint
        name: Run all linters
        entry: docker compose exec -T app make lint
        language: system
        always_run: true
        pass_filenames: false

    -   id: static-type-check
        name: Static type checker
        entry: docker compose exec -T app make static-type-check
        language: system
        always_run: true
        pass_filenames: false

    -   id: test
        name: Run tests
        entry: docker compose exec -T app make test
        language: system
        always_run: true
        pass_filenames: false

    - id: test-e2e
      name: Run tests e2e
      entry: docker compose exec -T app make test-e2e
      language: system
      always_run: true
      pass_filenames: false